name: hi_app
version: 1.0.0+1
description: A clean and visually appealing Flutter app that says Hi.
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  haptic_feedback: ^0.1.0
  flutter_svg: ^2.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/background/
    - assets/illustrations/ 